kind: pipeline
name: windows
type: docker

platform:
  os: windows
  arch: amd64

trigger:
  branch:
    - dev
    - conan_work
    - justin_test
  event:
    - push

steps:
  - name: Build
    image: artifactory.mersive.xyz/docker-public/windows-libwebrtc-builder
    commands:
      - ./build_windows.ps1
  - name: Conan Deploy
    image: artifactory.mersive.xyz/docker-public/windows-basic
    environment:
      CONAN_NON_INTERACTIVE: 1
      CONAN_REVISIONS_ENABLED: 1
      CONAN_LOGIN_USERNAME: ci-libwebrtc
      CONAN_PASSWORD:
        from_secret: artifactory-password
    commands:
      - ./deploy_windows.ps1
