kind: pipeline
name: windows
type: docker

platform:
  os: windows
  arch: amd64

trigger:
  branch:
    - dev
  event:
    - push

steps:
  - name: build
    image: grantsheehan/rust-windows #TODO: Use dedicated docker image
    environment:
      CONAN_NON_INTERACTIVE: 1
      CONAN_REVISIONS_ENABLED: 1
      CONAN_LOGIN_USERNAME: ci-libwebrtc
      CONAN_PASSWORD:
        from_secret: artifactory-password
    commands:
      - powershell Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope CurrentUser
      - powershell .\build_windows.ps1
