kind: pipeline
name: windows
type: docker

platform:
  os: windows
  arch: amd64

trigger:
  branch:
    - dev
    - conan_work
  event:
    - push

steps:
  - name: build
    image: artifactory.mersive.xyz/docker-public/libwebrtc-builder
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: artifactory-password
    commands:
      - powershell Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope CurrentUser
      - powershell .\build.ps1
