---
kind: pipeline
name: Perform Tagging
type: docker

platform:
  os: linux
  arch: amd64

trigger:
  branch:
    - dev
  event:
    - push

steps:
  - name: Create Automatic Tag
    image: alpine/git
    commands:
      - apk add --no-cache bash
      - exec ./version_tagging.sh
---
kind: pipeline
name: windows
type: docker

platform:
  os: windows
  arch: amd64

trigger:
  ref:
    - refs/tags/*
    - refs/pull/*/head

steps:
  - name: Versioning
    image: artifactory.mersive.xyz/docker-public/windows-basic:0.2
    when:
      event:
        - tag
    commands:
      - ./version_replacement.ps1
  - name: Build
    image: artifactory.mersive.xyz/docker-public/windows-libwebrtc-builder
    commands:
      - ./build_windows.ps1
  - name: Conan Deploy
    image: artifactory.mersive.xyz/docker-public/windows-basic
    environment:
      CONAN_NON_INTERACTIVE: 1
      CONAN_REVISIONS_ENABLED: 1
      CONAN_LOGIN_USERNAME: ci-libwebrtc
      CONAN_PASSWORD:
        from_secret: artifactory-password
    commands:
      - ./deploy_windows.ps1
