matrix:
  include:
    - os: osx
      osx_image: xcode11.5
      env: TARGET_CPU=x64
      addons:
        apt: *x64-apt

    - os: osx
      osx_image: xcode11.5
      env: TARGET_CPU=x64 CMAKE_BUILD_TYPE=Debug
      addons:
        apt: *x64-apt

language: cpp

before_install:
- DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
- mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
- |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
    mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
    export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    export CXX="g++-4.8" CC="gcc-4.8"
  else
    if ! brew ls --version cmake &>/dev/null; then brew update && brew install cmake; fi
  fi
- cd ${TRAVIS_BUILD_DIR}
- cmake --version

install:
- git submodule init
- git submodule update
- mkdir out
- cd out
- cmake -DBUILD_SAMPLE=1 -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DCMAKE_INSTALL_PREFIX=. -DTARGET_CPU=$TARGET_CPU ..

script:
- make -j 4 package
